### ISSUE TITLE
Flashing white screen when starting greeter.

### ISSUE THREAD

**Issue by beanaroo** [Antergos/lightdm-webkit2-greeter#45]
Regardless of theme used, when starting lightdm or initiating `dm-tool lock`, there is a blinding white flash before the greeter appears.

**Comment by lots0logs** [comment]
The greeter sets the background black as soon as it can. There's no way to make it happen any sooner I'm afraid. What are your system specs, btw?

**Comment by beanaroo** [comment]
Ah, I see that from the code commentary.  I'm running an i7-3612HQ, 8GB memory and SSD on Arch. I'm playing with implementing a black overlay that fades away once the web_view is loaded but my gtk skills are lacking. Hopefully I can share a proof of concept by the weekend.

**Comment by lots0logs** [comment]
That's odd. I have very similar system specs and I don't see the issue. For me it starts black, never white.  Fading in GTK doesn't work well. We used to let GTK handle the fade out before the greeter exits but we found that webkit renders the fade animations way better so we removed the GTK implementation.

**Comment by lots0logs** [comment]
@beanaroo Are you still experiencing this issue? Please let me know. Thanks!

**Comment by RealSpArTeN** [comment]
@lots0logs Can also confirm that this is happening to me as well, white screen is displayed for ~1.5 secs then disappears and greeter comes up

**Comment by lots0logs** [comment]
@samueldr Thanks for the PR :smiley: Though I'm afraid that the `gtk_widget_override_background_color` method was deprecated in GTK 3.16. The proper way to control the background color of a widget is now by using CSS (which we are already doing currently in the greeter)

**Comment by samueldr** [comment]
Then, it looks like that the Makefile condition for GTK 3.20 does not work properly. At least on archlinux, with gtk 3.20, the newly built code uses the non-gtk 3.20 CSS file, this is verified by checking the `.h` build artifact created, it uses `GtkWindow` instead of `window`.

Is it really necessary to have a different CSS file, one fore before 3.20, one for after? Wouldn't using a single css file with the rule set as `GtkWindow, window {...}` work? What would be the caveat using such a selector?

**Comment by lots0logs** [comment]
Good catch! Thanks to the way that GTK parses its CSS styles we can't combine the styles because GTK versions prior to `3.20` will ignore the style as invalid because they wont recognize the selector with no `.` or `#` prefixed to it (window). I only put them in separate files because I was in a hurry at that time and I have always intended to come back to it and do it better (just havent had time yet :pensive: ) I will try and look into the bug you found later tonight if you dont beat me to it :wink:

**Comment by samueldr** [comment]
Would GTK prior to 3.20 really ignore an [entire ruleset](https://www.w3.org/TR/2011/REC-CSS2-20110607/syndata.html#rule-sets) because of [one selector in a group](https://www.w3.org/TR/2011/REC-CSS2-20110607/selector.html#grouping) it deems invalid? The CSS spec is not clear whether grouping should mean the entire ruleset is invalid, but an [unknown type selector](https://www.w3.org/TR/2011/REC-CSS2-20110607/selector.html#type-selectors) should not be invalid. Though, GTK's CSS might be differing from the standard, in ways I cannot foresee.

Is there an OS that would be a good vm target to test a GTK 3.18/3.16 build of lightdm-webkit2-greeter? I would test whether combining the two stylesheets into one works properly, since for GTK 3.20 it does work properly.

**Comment by lots0logs** [comment]
Hmm..I'd say probably Linux Mint would be a good environment to test this in.
